### ISSUE TITLE
time complexity & accuracy

### ISSUE THREAD

**Issue by HARIHARAN1103** [Bergvca/string_grouper#1]
I just tested the algorithm for grouping of records which consist of company names, for my case its only 100 records works fine when using **ngram=2** . So i just gave kaggale data set consist of 6,60,000 records, but went on running for more than 65 minutes. Is this time complexity problem is common for very  one? Is there any way to make faster. 
And another one problem I faced is accuracy for some common records(example **11447 SECND STREET LLC and 11447 SECOND STREET LLC are not came to same group**, some records consist of numbers to differentiate companies but this algorithm combines them to same group. ). Is there any way to make better.
Thanks

**Comment by Bergvca** [comment]
Hi @HARIHARAN1103, thanks for your interest in this library!
As for the time complexity, this seems about right depending on the machine that you are using. On my laptop it takes about 45 minutes. Please note that there are 660k^2 potential comparisons to be made. 

The sparse_dot_topn library is multithreaded so using more cores should speed the process up, although I haven't seen the speedup that I would have expected with using multiple cores. 

For the example that you gave, when I use the default settings (ngrams = 3 and min_similarity = 0.8) the two strings are in the same group:

![image](https://user-images.githubusercontent.com/11998981/71920702-5cf89e80-3155-11ea-929d-3ddf4cf39d27.png)
