### ISSUE TITLE
pip install string-grouper doesn't work

### ISSUE THREAD

**Issue by AlmogW** [Bergvca/string_grouper#11]
Hi guys, 

I tried to install string-grouper using anaconda prompt and got the following error. What could be the issue?  Thanks!

ERROR: Could not find a version that satisfies the requirement string-grouper (from versions: none)
ERROR: No matching distribution found for string-grouper

**Comment by Bergvca** [comment]
Hi @AlmogW 

What command are you using? You mention you are using anaconda prompt, does that mean you are using conda install, instead of pip?

**Comment by AlmogW** [comment]
Hi Chris,

First, I really appreciate your help. Secondly, I apologize, my python
version wasn't up to date.

All the best,
Al

**Comment by Bergvca** [comment]
No problem!
