### ISSUE TITLE
Setting min_similarity missing in _init_

### ISSUE THREAD

**Issue by aksg87** [Bergvca/string_grouper#16]
Is there a clear way to set the min_similarity for the grouping? This doesn't seem supported. For example:

```
string_grouper = StringGrouper(
    dataset["Description"].astype(str),
    min_similarity=0.1,  # <-- not supported?
).fit()
```

**Comment by Bergvca** [comment]
Hi @aksg87 ,

This should work fine, the StringGrouper object passes all keyword arguments to a *StringGrouperConfig* object, which also contains the min_similarity argument. 

Chris
