### ISSUE TITLE
Is it possible to swap the tfidfvectorizer with different vectorizer?

### ISSUE THREAD

**Issue by donnydongchen** [Bergvca/string_grouper#2]
I absolutely love this library! Lightning-fast! 

This is not really an issue, but a discussion.

I'm just wondering if it makes sense to be able to swap the tfidfvectorizer with other context-based embedding models/vectorizers, e.g., fasttext, word2vec. That is, compute the cosine similarity for the matrices from custom embedding models other than just using tf-idf matrix.

**Comment by Bergvca** [comment]
Hi Donny,

Thanks! You could definitely swap the tf-vectorizer, but it's dependent on your use case. E.g. word2vec (in combination with vector averaging for example) could be used to find similar documents whereas string_grouper is more geared towards short strings. One issue would be that the grouping algorithm takes the whole string currently as the group identifier. This could be changed to the row index for example. You also need to change the cosine similarity method, but that shouldn't be a problem.

**Comment by donnydongchen** [comment]
Thanks for your reply Chris! Yeah I agree that it depends on the use case, so I will share a bit of my use case here and someone may come across the same scenario:

**Problem Statement:** Find all matches in between two series. One series has all the messy names, and another one has the unified names.

I have a character-based fasttext embedding model that had already captured the hidden semantic information from a huge corpus that (hopefully) contains both messy and unified names. That's why I would like to drop in and use fasttext instead of tfidf vectorizer to transform the two series.

I'm not sure if Gensim's fasttext has a `transform` method as friendly as sklearn's `tfidfvectorizer` (like you said, one may have to do vector averaging). But I will let you know if I got it all working and you are interested :)
