### ISSUE TITLE
does this work on python3.7?

### ISSUE THREAD

**Issue by zhihongchensg** [Bergvca/string_grouper#3]
i tried pip install but it gave an error  error: Microsoft Visual C++ 14.0 is required.

Am running C++ 19.  

Appreciate your help.

thanks,

**Comment by qinyufm** [comment]
You need install VC++ build tools.

**Comment by Bergvca** [comment]
@zhihongchensg did that answer your question?

**Comment by Norah8** [comment]
@Bergvca I have the same issue, can't install it because of vc++ although I already installed vc++.

**Comment by monikrish2698** [comment]
Hey the issue is with sparse_dot_topn package which I believe is used in string grouper. 
1. Try installing sparse_dot_topn using conda install -c conda-forge sparse_dot_topn
2. the do pip install stringer-grouper
It worked for me!
