### ISSUE TITLE
Index mismatch may lead to unintended consequences!

### ISSUE THREAD

**Issue by ParticularMiner** [Bergvca/string_grouper#35]
# Issue: Unequal pandas Indexes of Input and Output data can cause unintended consequences 

The following describes the problem, and how it can be fixed.

```python
import pandas as pd
from string_grouper import group_similar_strings
```

Let's import some data:

```python
companies = pd.read_csv('data/sec__edgar_company_info.csv')[0:50000]
```

```python
companies
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Line Number</th>
      <th>Company Name</th>
      <th>Company CIK Key</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>!J INC</td>
      <td>1438823</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>#&#x2060;1 A LIFESAFER HOLDINGS, INC.</td>
      <td>1509607</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>#&#x2060;1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>1457512</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>#&#x2060;1 PAINTBALL CORP</td>
      <td>1433777</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>$ LLC</td>
      <td>1427189</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>49995</th>
      <td>49996</td>
      <td>BABB DOUGLAS J</td>
      <td>1190359</td>
    </tr>
    <tr>
      <th>49996</th>
      <td>49997</td>
      <td>BABB HENRY C</td>
      <td>1193948</td>
    </tr>
    <tr>
      <th>49997</th>
      <td>49998</td>
      <td>BABB INTERNATIONAL INC</td>
      <td>1139504</td>
    </tr>
    <tr>
      <th>49998</th>
      <td>49999</td>
      <td>BABB JACK J</td>
      <td>1280368</td>
    </tr>
    <tr>
      <th>49999</th>
      <td>50000</td>
      <td>BABB JAMES G. III</td>
      <td>1575424</td>
    </tr>
  </tbody>
</table>
<p>50000 rows &times; 3 columns</p>
</div>

Let's give the data a different (unique-valued) index as most users might do:

```python
companies.set_index(['Line Number', 'Company CIK Key'], inplace=True, verify_integrity=True)
```

Display the data to see the change:

```python
companies
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>Company Name</th>
    </tr>
    <tr>
      <th>Line Number</th>
      <th>Company CIK Key</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <th>1438823</th>
      <td>!J INC</td>
    </tr>
    <tr>
      <th>2</th>
      <th>1509607</th>
      <td>#&#x2060;1 A LIFESAFER HOLDINGS, INC.</td>
    </tr>
    <tr>
      <th>3</th>
      <th>1457512</th>
      <td>#&#x2060;1 ARIZONA DISCOUNT PROPERTIES LLC</td>
    </tr>
    <tr>
      <th>4</th>
      <th>1433777</th>
      <td>#&#x2060;1 PAINTBALL CORP</td>
    </tr>
    <tr>
      <th>5</th>
      <th>1427189</th>
      <td>$ LLC</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th>49996</th>
      <th>1190359</th>
      <td>BABB DOUGLAS J</td>
    </tr>
    <tr>
      <th>49997</th>
      <th>1193948</th>
      <td>BABB HENRY C</td>
    </tr>
    <tr>
      <th>49998</th>
      <th>1139504</th>
      <td>BABB INTERNATIONAL INC</td>
    </tr>
    <tr>
      <th>49999</th>
      <th>1280368</th>
      <td>BABB JACK J</td>
    </tr>
    <tr>
      <th>50000</th>
      <th>1575424</th>
      <td>BABB JAMES G. III</td>
    </tr>
  </tbody>
</table>
<p>50000 rows &times; 1 columns</p>
</div>

Now let's do some grouping as usual:

```python
grouped_data = group_similar_strings(companies['Company Name'])
```

Notice that the (default) index of the output (`grouped_data`) is different from that of the input DataFrame (`companies`): for instance, it starts from 0 instead of 1:

```python
grouped_data
```

    0                                    !J INC
    1             #1 A LIFESAFER HOLDINGS, INC.
    2        #1 ARIZONA DISCOUNT PROPERTIES LLC
    3                         #1 PAINTBALL CORP
    4                                     $ LLC
                            ...                
    49995                        BABB DOUGLAS J
    49996                          BABB HENRY C
    49997                BABB INTERNATIONAL INC
    49998                           BABB JACK J
    49999                     BABB JAMES G. III
    Length: 50000, dtype: object

This causes unintended consequences when for example, blindly assigning this to new columns in the input DataFrame:

```python
companies['Group Name'] = grouped_data
```

Notice the incorrect group names (`NaN` values) in each row of the `companies` DataFrame:

```python
companies
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>Company Name</th>
      <th>Group Name</th>
    </tr>
    <tr>
      <th>Line Number</th>
      <th>Company CIK Key</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <th>1438823</th>
      <td>!J INC</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <th>1509607</th>
      <td>#&#x2060;1 A LIFESAFER HOLDINGS, INC.</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3</th>
      <th>1457512</th>
      <td>#&#x2060;1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4</th>
      <th>1433777</th>
      <td>#&#x2060;1 PAINTBALL CORP</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <th>1427189</th>
      <td>$ LLC</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>49996</th>
      <th>1190359</th>
      <td>BABB DOUGLAS J</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>49997</th>
      <th>1193948</th>
      <td>BABB HENRY C</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>49998</th>
      <th>1139504</th>
      <td>BABB INTERNATIONAL INC</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>49999</th>
      <th>1280368</th>
      <td>BABB JACK J</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>50000</th>
      <th>1575424</th>
      <td>BABB JAMES G. III</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>50000 rows &times; 2 columns</p>
</div>

Why did this happen?  &mdash; Because in many pandas operations, including column/row value assignment, ***the indexes of the values being assigned must match those of the values being replaced***.

How to fix this?  &mdash; Simply ensure that the index of the output of our functions such as `group_similar_strings()` and `match_most_similar()` is exactly the same as that of the input strings.  

Let's illustrate this here:

```python
grouped_data.index = companies.index
```

See how the output Dataframe `grouped_data` changed:

```python
grouped_data
```

    Line Number  Company CIK Key
    1            1438823                                        !J INC
    2            1509607                 #1 A LIFESAFER HOLDINGS, INC.
    3            1457512            #1 ARIZONA DISCOUNT PROPERTIES LLC
    4            1433777                             #1 PAINTBALL CORP
    5            1427189                                         $ LLC
                                                   ...                
    49996        1190359                                BABB DOUGLAS J
    49997        1193948                                  BABB HENRY C
    49998        1139504                        BABB INTERNATIONAL INC
    49999        1280368                                   BABB JACK J
    50000        1575424                             BABB JAMES G. III
    Length: 50000, dtype: object

Now let's perform the column assignment:

```python
companies['Group Name'] = grouped_data
```

Now everything is as it should be:

```python
companies
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>Company Name</th>
      <th>Group Name</th>
    </tr>
    <tr>
      <th>Line Number</th>
      <th>Company CIK Key</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <th>1438823</th>
      <td>!J INC</td>
      <td>!J INC</td>
    </tr>
    <tr>
      <th>2</th>
      <th>1509607</th>
      <td>#&#x2060;1 A LIFESAFER HOLDINGS, INC.</td>
      <td>#&#x2060;1 A LIFESAFER HOLDINGS, INC.</td>
    </tr>
    <tr>
      <th>3</th>
      <th>1457512</th>
      <td>#&#x2060;1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>#&#x2060;1 ARIZONA DISCOUNT PROPERTIES LLC</td>
    </tr>
    <tr>
      <th>4</th>
      <th>1433777</th>
      <td>#&#x2060;1 PAINTBALL CORP</td>
      <td>#&#x2060;1 PAINTBALL CORP</td>
    </tr>
    <tr>
      <th>5</th>
      <th>1427189</th>
      <td>$ LLC</td>
      <td>$ LLC</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>49996</th>
      <th>1190359</th>
      <td>BABB DOUGLAS J</td>
      <td>BABB DOUGLAS J</td>
    </tr>
    <tr>
      <th>49997</th>
      <th>1193948</th>
      <td>BABB HENRY C</td>
      <td>BABB HENRY C</td>
    </tr>
    <tr>
      <th>49998</th>
      <th>1139504</th>
      <td>BABB INTERNATIONAL INC</td>
      <td>BABB INTERNATIONAL INC</td>
    </tr>
    <tr>
      <th>49999</th>
      <th>1280368</th>
      <td>BABB JACK J</td>
      <td>BABB JACK J</td>
    </tr>
    <tr>
      <th>50000</th>
      <th>1575424</th>
      <td>BABB JAMES G. III</td>
      <td>BABB JAMES G. III</td>
    </tr>
  </tbody>
</table>
<p>50000 rows &times; 2 columns</p>
</div>

Thus if we do not wish the user to go through the hassle of doing all this himself/herself, then this may mean capturing the index of the input Series/DataFrame in the StringGrouper instance and stashing it somewhere until the grouping is done; then reassigning it to the index of the output Series/DataFrame just before return.

What do you think?

**Comment by Bergvca** [comment]
Hi @ParticularMiner, I fully agree that we should return the original indices. I probably should have done that right from the start. The problem is that we are dropping the indices right away. I think we can just remove the reset_index calls (everywhere). I mentioned that here as well: https://github.com/Bergvca/string_grouper/issues/18#issuecomment-771964700. We just need to do the following (I think): 

* Not resetting the indices in the constructor
* Updating the get_matches to access by position (e.g. .iloc) and not drop indices

**Comment by ParticularMiner** [comment]
Oh yes.  @justasojourner mentioned this to me earlier too.  
I seem to have missed your earlier comment in #18.  Please see [PR34](https://github.com/Bergvca/string_grouper/pull/34#issuecomment-799565359) for the resolution of this issue.
