### ISSUE TITLE
Do the groups returned by String_Grouper follow the transitive property? 

### ISSUE THREAD

**Issue by bmanczak** [Bergvca/string_grouper#70]
Let's say our min_similarity is 0.8. Then if similarity(A,B) = 0.9, similarity(B,C)=0.85 and similarity(A,C)=0.7 will A,B and C all be in the same group?

Thanks!

**Comment by ParticularMiner** [comment]
@bmanczak 

Yes.  Follow [this link](https://github.com/Bergvca/string_grouper#deduplicate-a-single-data-set-and-show-items-with-most-duplicates).

**Comment by bmanczak** [comment]
Thanks!
