### ISSUE TITLE
Could not install string-grouper

### ISSUE THREAD

**Issue by campbellalex321** [Bergvca/string_grouper#77]
when I enter the command pip install string_grouper I get the following errors 

LINK : fatal error LNK1158: cannot run 'rc.exe'
ERROR: Failed building wheel for topn
ERROR: Could not build wheels for sparse-dot-topn-for-blocks which use PEP 517 and cannot be installed directly

**Comment by ParticularMiner** [comment]
Hi @campbellalex321 

It seems you need to check whether your Visual Studio C/C++ compiler has been setup properly.
See https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe

**Comment by campbellalex321** [comment]
thanks @ParticularMiner I uninstalled Visual Studio and just reinstalled the 2022 version and that seemed to do it ( I bet I could have just updated it, but oh well :D thank you! )
