### ISSUE TITLE
able to change default cosine similarity of .8? 

### ISSUE THREAD

**Issue by campbellalex321** [Bergvca/string_grouper#78]
I noticed that the default cosine similarity is .8, but it seems like it's not bringing back matches that are just one character in some cases and I was wondering if there was a way I could bring the cosine similarity as a parameter? I looked at your examples and seemed like there was nothing that did that. Or would I just have to import the class and change the default value myself?

**Comment by ParticularMiner** [comment]
@campbellalex321 

The relevant parameter is `min_similarity`.  Follow [this link](https://github.com/Bergvca/string_grouper#options).

**Comment by campbellalex321** [comment]
oh thank you! Shoot can't believe I missed that!
