### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ZhimingMei** [Bergvca/string_grouper#89]
When I try to import string_grouper in my project, it reports an error saying that: 'numpy.core.multiarray failed to import'.

I try to upgrade (and also downgrade) my numpy version, but still it does not work...

Here's my version list of python modules:
- numpy 1.22.4
- string_grouper 0.6.1

I wonder how to solve this import error. Thx.

**Comment by ZhimingMei** [comment]
Okay..., it seems that this error happens when the version of numpy package is incompatible with string_grouper.

Now I tried again with numpy 1.23.x, and it finally works.

**Comment by Bergvca** [comment]
Hi @ZhimingMei, do you know if it works with the latest version of numpy (1.24.0)?

**Comment by ZhimingMei** [comment]
Yes, it works. I just tried it again with numpy (1.24.0).
